"""currencies display metadata

Revision ID: 053ea46ad963
Revises: fc4066bfbbeb
Create Date: 2026-06-09 15:17:29.601164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053ea46ad963'
down_revision: Union[str, None] = 'fc4066bfbbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('symbol', sa.String(length=10), server_default='', nullable=False))
    op.add_column('currencies', sa.Column('display_decimals', sa.SmallInteger(), server_default='2', nullable=False))
    # ### end Alembic commands ###

    currencies = sa.table(
        "currencies",
        sa.column("id", sa.SmallInteger),
        sa.column("symbol", sa.String),
        sa.column("display_decimals", sa.SmallInteger),
    )
    for _id, _symbol, _decimals in [
        (1, "$", 0),
        (2, "U$S", 2),
        (3, "U$S", 2),
        (4, "UI", 2),
        (5, "UR", 2),
    ]:
        op.execute(
            currencies.update().where(currencies.c.id == _id).values(symbol=_symbol, display_decimals=_decimals)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'display_decimals')
    op.drop_column('currencies', 'symbol')
    # ### end Alembic commands ###
