"""create credit_card_networks

Revision ID: 20078984c6f3
Revises: e212e33bdbfc
Create Date: 2026-06-06 18:16:32.129012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20078984c6f3'
down_revision: Union[str, None] = 'e212e33bdbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card_networks',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'code', name='uq_credit_card_networks_country_code_code')
    )
    op.bulk_insert(
        sa.table(
            "credit_card_networks",
            sa.column("id", sa.SmallInteger),
            sa.column("country_code", sa.String),
            sa.column("code", sa.String),
            sa.column("name", sa.String),
        ),
        [
            {"id": 1, "country_code": "UY", "code": "visa", "name": "Visa"},
            {"id": 2, "country_code": "UY", "code": "mastercard", "name": "Mastercard"},
            {"id": 3, "country_code": "UY", "code": "amex", "name": "Amex"},
            {"id": 4, "country_code": "UY", "code": "oca", "name": "OCA"},
            {"id": 5, "country_code": "UY", "code": "diners", "name": "Diners"},
            {"id": 6, "country_code": "UY", "code": "cabal", "name": "Cabal"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card_networks')
    # ### end Alembic commands ###
