"""create plans and plan_movements

Revision ID: 2960225ce5c0
Revises: 6b8f05668018
Create Date: 2026-06-07 17:41:42.888536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2960225ce5c0'
down_revision: Union[str, None] = '6b8f05668018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_engine_generated', sa.Boolean(), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dial_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dial_currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('goal_kind', sa.Enum('ahorro_total', name='plan_goal_kind'), nullable=True),
    sa.Column('goal_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('goal_currency_id', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dial_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['goal_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('ingreso', 'deuda_informal', 'prestamo', name='plan_movement_kind'), nullable=False),
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('principal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('income_duration_months', sa.SmallInteger(), nullable=True),
    sa.Column('installment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('installment_start_date', sa.Date(), nullable=True),
    sa.Column('total_installments', sa.SmallInteger(), nullable=True),
    sa.Column('financing_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overdue_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rates_add_vat', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_movements')
    op.drop_table('plans')
    sa.Enum(name='plan_movement_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='plan_goal_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
