"""create obligations

Revision ID: 29afc7c4c130
Revises: 53624a190a78
Create Date: 2026-06-08 03:29:54.544188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29afc7c4c130'
down_revision: Union[str, None] = '53624a190a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('obligation_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('priority_level', sa.SmallInteger(), nullable=False),
    sa.Column('institution_id', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('is_monthly_recurring', sa.Boolean(), nullable=False),
    sa.Column('due_day', sa.SmallInteger(), nullable=True),
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_installments', sa.SmallInteger(), nullable=True),
    sa.Column('first_due_date', sa.Date(), nullable=True),
    sa.Column('shift_weekends', sa.Boolean(), nullable=False),
    sa.Column('financing_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overdue_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rates_add_vat', sa.Boolean(), nullable=False),
    sa.Column('origin_obligation_id', sa.UUID(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_findings', sa.Text(), nullable=False),
    sa.Column('user_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['obligation_type_id'], ['obligation_types.id'], ),
    sa.ForeignKeyConstraint(['origin_obligation_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['priority_level'], ['priority_levels.level'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_origin_obligation_id'), 'obligations', ['origin_obligation_id'], unique=False)
    op.create_index(op.f('ix_obligations_user_id'), 'obligations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligations_user_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_origin_obligation_id'), table_name='obligations')
    op.drop_table('obligations')
    # ### end Alembic commands ###
