"""create credit_card_item_types

Revision ID: 342b00cc89fc
Revises: 20078984c6f3
Create Date: 2026-06-06 18:17:52.077432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342b00cc89fc'
down_revision: Union[str, None] = '20078984c6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card_item_types',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_credit_card_item_types_code')
    )
    op.bulk_insert(
        sa.table(
            "credit_card_item_types",
            sa.column("id", sa.SmallInteger),
            sa.column("code", sa.String),
            sa.column("name", sa.String),
            sa.column("description", sa.String),
        ),
        [
            {"id": 1, "code": "compra", "name": "Compra", "description": "Un consumo común con la tarjeta: bienes o servicios adquiridos por el usuario."},
            {"id": 2, "code": "interes", "name": "Interés", "description": "Cargo por financiación o mora generado por el saldo de la tarjeta."},
            {"id": 3, "code": "suscripcion", "name": "Suscripción", "description": "Un cargo recurrente por un servicio que se renueva periódicamente."},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card_item_types')
    # ### end Alembic commands ###
