"""create obligation_types

Revision ID: 34cee9d93d24
Revises: 342b00cc89fc
Create Date: 2026-06-06 18:19:42.454298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cee9d93d24'
down_revision: Union[str, None] = '342b00cc89fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligation_types',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('obligation_kind', sa.Enum('gasto', 'deuda', 'deuda_abierta', name='obligation_kind'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('default_priority_level', sa.SmallInteger(), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['default_priority_level'], ['priority_levels.level'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_obligation_types_code')
    )
    op.bulk_insert(
        sa.table(
            "obligation_types",
            sa.column("id", sa.SmallInteger),
            sa.column("obligation_kind", sa.String),
            sa.column("code", sa.String),
            sa.column("name", sa.String),
            sa.column("description", sa.String),
            sa.column("default_priority_level", sa.SmallInteger),
            sa.column("visible", sa.Boolean),
        ),
        [
            {"id": 1, "obligation_kind": "gasto", "code": "alquiler", "name": "Alquiler / hipoteca", "description": "El techo donde vivís: alquiler o cuota de la hipoteca.", "default_priority_level": 2, "visible": True},
            {"id": 2, "obligation_kind": "gasto", "code": "utilities", "name": "Servicios básicos", "description": "Lo que no podés cortar: luz, agua, gas, internet.", "default_priority_level": 2, "visible": True},
            {"id": 3, "obligation_kind": "gasto", "code": "salud", "name": "Salud", "description": "Mutualista, medicación, emergencia móvil.", "default_priority_level": 2, "visible": True},
            {"id": 4, "obligation_kind": "gasto", "code": "subscriptions", "name": "Suscripciones", "description": "Servicios que se debitan solos: streaming, gimnasio, apps.", "default_priority_level": 2, "visible": True},
            {"id": 5, "obligation_kind": "gasto", "code": "otros_gastos", "name": "Otros gastos", "description": "Cualquier gasto que no encaje en los anteriores.", "default_priority_level": 3, "visible": True},
            {"id": 6, "obligation_kind": "deuda", "code": "adelanto_sueldo", "name": "Adelanto de sueldo", "description": "Pediste plata a cuenta del próximo sueldo; el empleador la descuenta cuando cobrás. La carga el sistema, no vos.", "default_priority_level": 1, "visible": True},
            {"id": 7, "obligation_kind": "deuda", "code": "atraso", "name": "Atraso u obligación", "description": "Algo que se atrasó y se acumula solo: impuestos, servicios o alquiler vencidos, multas.", "default_priority_level": 4, "visible": True},
            {"id": 8, "obligation_kind": "deuda_abierta", "code": "informal", "name": "Deuda informal", "description": "Le debés a una persona: familiar, amigo, fiado. Sin cronograma fijo de pagos; pagás cuando podés.", "default_priority_level": 6, "visible": True},
            {"id": 9, "obligation_kind": "deuda", "code": "otras_deudas", "name": "Otra deuda", "description": "Cualquier deuda que no encaje claro en las anteriores.", "default_priority_level": 4, "visible": True},
            {"id": 10, "obligation_kind": "deuda", "code": "prestamo", "name": "Préstamo en cuotas", "description": "Tiene un fin conocido: préstamo personal, de auto, hipoteca o compra en cuotas.", "default_priority_level": 4, "visible": True},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obligation_types')
    sa.Enum(name="obligation_kind").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
