"""create currency_rates

Revision ID: 44c310780edb
Revises: 628d75462b82
Create Date: 2026-06-06 14:18:17.201304

"""
from datetime import date, timedelta
from decimal import Decimal
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c310780edb'
down_revision: Union[str, None] = '628d75462b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('is_projected', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('currency_id', 'rate_date')
    )
    rates = {2: "39", 3: "41", 4: "6.55", 5: "1921.36"}
    table = sa.table(
        "currency_rates",
        sa.column("currency_id", sa.SmallInteger),
        sa.column("rate_date", sa.Date),
        sa.column("value", sa.Numeric),
        sa.column("is_projected", sa.Boolean),
    )
    rows = []
    current = date(2026, 4, 1)
    end = date(2027, 12, 31)
    while current <= end:
        for currency_id, value in rates.items():
            rows.append(
                {
                    "currency_id": currency_id,
                    "rate_date": current,
                    "value": Decimal(value),
                    "is_projected": True,
                }
            )
        current += timedelta(days=1)
    op.bulk_insert(table, rows)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
