"""is_auto_generated en plan_movements y cash_flow_payments

Revision ID: 4969c94ebafb
Revises: 35ebf35bc341
Create Date: 2026-06-10 16:42:32.315921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4969c94ebafb'
down_revision: Union[str, None] = '35ebf35bc341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_flow_payments', sa.Column('is_auto_generated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('plan_movements', sa.Column('is_auto_generated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_movements', 'is_auto_generated')
    op.drop_column('cash_flow_payments', 'is_auto_generated')
    # ### end Alembic commands ###
