"""create countries

Revision ID: 4f5760921fc1
Revises: 
Create Date: 2026-06-06 04:13:47.425340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5760921fc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=4, scale=2), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###

    # Seed inicial: Uruguay (tabla maestra administrada por el admin).
    op.bulk_insert(
        sa.table(
            "countries",
            sa.column("code", sa.String),
            sa.column("name", sa.String),
            sa.column("visible", sa.Boolean),
            sa.column("vat_rate", sa.Numeric),
        ),
        [{"code": "UY", "name": "Uruguay", "visible": True, "vat_rate": 22.00}],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
