"""create cash_flow_entries and cash_flow_payments

Revision ID: 53624a190a78
Revises: 2960225ce5c0
Create Date: 2026-06-07 18:30:32.577038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53624a190a78'
down_revision: Union[str, None] = '2960225ce5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_flow_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('financing_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overdue_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('issue_year', sa.SmallInteger(), nullable=True),
    sa.Column('issue_month', sa.SmallInteger(), nullable=True),
    sa.Column('minimum_payment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source_type', sa.Enum('gasto', 'deuda', 'deuda_abierta', 'ingreso', 'plan_movimiento', 'plan_movimiento_entrada', 'tarjeta_credito', name='cash_flow_source_type'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_flow_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cash_flow_entry_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cash_flow_entry_id'], ['cash_flow_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_flow_payments')
    op.drop_table('cash_flow_entries')
    sa.Enum(name='cash_flow_source_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
