"""create currencies

Revision ID: 628d75462b82
Revises: 6df27db5fb1e
Create Date: 2026-06-06 14:16:50.191616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628d75462b82'
down_revision: Union[str, None] = '6df27db5fb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('is_legal_tender', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allowed_in_credit_card', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        sa.table(
            "currencies",
            sa.column("id", sa.SmallInteger),
            sa.column("country_code", sa.String),
            sa.column("name", sa.String),
            sa.column("is_legal_tender", sa.Boolean),
            sa.column("allowed_in_credit_card", sa.Boolean),
        ),
        [
            {"id": 1, "country_code": "UY", "name": "Peso", "is_legal_tender": True, "allowed_in_credit_card": True},
            {"id": 2, "country_code": "UY", "name": "Dólar compra", "is_legal_tender": False, "allowed_in_credit_card": False},
            {"id": 3, "country_code": "UY", "name": "Dólar", "is_legal_tender": False, "allowed_in_credit_card": True},
            {"id": 4, "country_code": "UY", "name": "Unidad Indexada", "is_legal_tender": False, "allowed_in_credit_card": False},
            {"id": 5, "country_code": "UY", "name": "Unidad Reajustable", "is_legal_tender": False, "allowed_in_credit_card": False},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currencies')
    # ### end Alembic commands ###
