"""create incomes

Revision ID: 6b8f05668018
Revises: b62be030ba67
Create Date: 2026-06-07 14:20:46.296145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8f05668018'
down_revision: Union[str, None] = 'b62be030ba67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('income_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('is_monthly_recurring', sa.Boolean(), nullable=False),
    sa.Column('payment_day', sa.SmallInteger(), nullable=True),
    sa.Column('first_income_date', sa.Date(), nullable=True),
    sa.Column('total_months', sa.SmallInteger(), nullable=True),
    sa.Column('shift_weekends', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['income_type_id'], ['income_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incomes')
    # ### end Alembic commands ###
