"""create credit card tables

Revision ID: 7e12cf8ac5e3
Revises: 29afc7c4c130
Create Date: 2026-06-08 15:29:20.386650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e12cf8ac5e3'
down_revision: Union[str, None] = '29afc7c4c130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.SmallInteger(), nullable=False),
    sa.Column('card_network_id', sa.SmallInteger(), nullable=False),
    sa.Column('current_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_day', sa.SmallInteger(), nullable=False),
    sa.Column('financing_rate_local', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overdue_rate_local', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('financing_rate_usd', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overdue_rate_usd', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rates_add_vat', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_findings', sa.Text(), nullable=False),
    sa.Column('user_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_network_id'], ['credit_card_networks.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_cards_user_id'), 'credit_cards', ['user_id'], unique=False)
    op.create_index('uq_credit_cards_user_institution_network', 'credit_cards', ['user_id', 'institution_id', 'card_network_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('staging_credit_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.SmallInteger(), nullable=True),
    sa.Column('card_network_id', sa.SmallInteger(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('current_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_local', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('minimum_payment_local', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('minimum_payment_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('financing_rate_local', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overdue_rate_local', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('financing_rate_usd', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overdue_rate_usd', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rates_add_vat', sa.Boolean(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_findings', sa.Text(), nullable=False),
    sa.Column('user_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_network_id'], ['credit_card_networks.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_staging_credit_cards_user_id')
    )
    op.create_table('credit_card_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_card_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('charge_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('total_installments', sa.SmallInteger(), nullable=True),
    sa.Column('item_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('last_statement_closing_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['credit_card_item_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_card_id', sa.UUID(), nullable=False),
    sa.Column('issue_year', sa.SmallInteger(), nullable=False),
    sa.Column('issue_month', sa.SmallInteger(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_local', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_payment_local', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_payment_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_card_id', 'issue_month', 'issue_year', name='uq_credit_card_statements_period')
    )
    op.create_table('staging_credit_card_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staging_credit_card_id', sa.UUID(), nullable=False),
    sa.Column('charge_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency_id', sa.SmallInteger(), nullable=True),
    sa.Column('current_installment', sa.SmallInteger(), nullable=True),
    sa.Column('total_installments', sa.SmallInteger(), nullable=True),
    sa.Column('item_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['credit_card_item_types.id'], ),
    sa.ForeignKeyConstraint(['staging_credit_card_id'], ['staging_credit_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card_statement_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_card_statement_id', sa.UUID(), nullable=False),
    sa.Column('charge_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('current_installment', sa.SmallInteger(), nullable=True),
    sa.Column('total_installments', sa.SmallInteger(), nullable=True),
    sa.Column('item_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_statement_id'], ['credit_card_statements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['credit_card_item_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card_statement_items')
    op.drop_table('staging_credit_card_items')
    op.drop_table('credit_card_statements')
    op.drop_table('credit_card_purchases')
    op.drop_table('staging_credit_cards')
    op.drop_index('uq_credit_cards_user_institution_network', table_name='credit_cards', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_credit_cards_user_id'), table_name='credit_cards')
    op.drop_table('credit_cards')
    # ### end Alembic commands ###
