"""create purchases and purchase_categories

Revision ID: 8ece9281cc33
Revises: 4969c94ebafb
Create Date: 2026-06-10 22:37:49.915291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ece9281cc33'
down_revision: Union[str, None] = '4969c94ebafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_categories',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_purchase_categories_code')
    )
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credit_card_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['purchase_categories.id'], ),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchases_user_id_purchase_date', 'purchases', ['user_id', 'purchase_date'], unique=False)
    # ### end Alembic commands ###
    op.bulk_insert(
        sa.table(
            "purchase_categories",
            sa.column("id", sa.SmallInteger),
            sa.column("code", sa.String),
            sa.column("name", sa.String),
            sa.column("emoji", sa.String),
        ),
        [
            {"id": 1, "code": "comida", "name": "Comida", "emoji": "🍔"},
            {"id": 2, "code": "supermercado", "name": "Supermercado", "emoji": "🛒"},
            {"id": 3, "code": "transporte", "name": "Transporte", "emoji": "🚌"},
            {"id": 4, "code": "hogar", "name": "Hogar", "emoji": "🏠"},
            {"id": 5, "code": "salud", "name": "Salud", "emoji": "💊"},
            {"id": 6, "code": "ocio", "name": "Ocio", "emoji": "🎮"},
            {"id": 7, "code": "ropa", "name": "Ropa", "emoji": "👕"},
            {"id": 8, "code": "servicios", "name": "Servicios", "emoji": "💡"},
            {"id": 9, "code": "suscripciones", "name": "Suscripciones", "emoji": "📺"},
            {"id": 10, "code": "cafe", "name": "Café", "emoji": "☕"},
            {"id": 11, "code": "mascotas", "name": "Mascotas", "emoji": "🐶"},
            {"id": 12, "code": "otros", "name": "Otros", "emoji": "🧩"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchases_user_id_purchase_date', table_name='purchases')
    op.drop_table('purchases')
    op.drop_table('purchase_categories')
    # ### end Alembic commands ###
