"""create priority_levels

Revision ID: ad423b18d25a
Revises: 44c310780edb
Create Date: 2026-06-06 14:22:21.049074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad423b18d25a'
down_revision: Union[str, None] = '44c310780edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority_levels',
    sa.Column('level', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('level')
    )
    op.bulk_insert(
        sa.table(
            "priority_levels",
            sa.column("level", sa.SmallInteger),
            sa.column("name", sa.String),
            sa.column("description", sa.String),
        ),
        [
            {"level": 1, "name": "Ineludible", "description": "No pasa por tu decisión: se descuenta solo (ej. adelanto de sueldo que el empleador retiene del próximo cobro). Lo asigna el sistema, no se elige."},
            {"level": 2, "name": "Esencial", "description": "Sin esto no podés vivir ni funcionar: techo, comida, salud, luz, agua, transporte."},
            {"level": 3, "name": "Obligación crítica", "description": "Si no lo pagás, te embargan o te cortan: impuestos atrasados, deuda en mora."},
            {"level": 4, "name": "Obligación prioritaria", "description": "Crece rápido o conviene cubrirla cuanto antes: préstamo con tasa alta."},
            {"level": 5, "name": "Obligación manejable", "description": "Tenés que pagarla pero no te asfixia: interés bajo, o algo que le debés a alguien de confianza."},
            {"level": 6, "name": "Ajustable", "description": "Está en tus manos moverlo o achicarlo: suscripciones y gastos personales."},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priority_levels')
    # ### end Alembic commands ###
