"""create income_types

Revision ID: b62be030ba67
Revises: 34cee9d93d24
Create Date: 2026-06-06 18:21:12.540400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62be030ba67'
down_revision: Union[str, None] = '34cee9d93d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_types',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_income_types_code')
    )
    op.bulk_insert(
        sa.table(
            "income_types",
            sa.column("id", sa.SmallInteger),
            sa.column("code", sa.String),
            sa.column("name", sa.String),
            sa.column("visible", sa.Boolean),
        ),
        [
            {"id": 1, "code": "sueldo", "name": "Sueldo", "visible": True},
            {"id": 2, "code": "pension", "name": "Pensión / jubilación", "visible": True},
            {"id": 3, "code": "alquiler", "name": "Alquiler que cobra", "visible": True},
            {"id": 4, "code": "freelance", "name": "Freelance", "visible": True},
            {"id": 5, "code": "comisiones", "name": "Comisiones", "visible": True},
            {"id": 6, "code": "horas_extra", "name": "Horas extra", "visible": True},
            {"id": 7, "code": "aguinaldo", "name": "Aguinaldo", "visible": True},
            {"id": 8, "code": "devolucion_impuestos", "name": "Devolución de impuestos", "visible": True},
            {"id": 9, "code": "otro", "name": "Otro", "visible": True},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_types')
    # ### end Alembic commands ###
