"""create institutions

Revision ID: b78d832902cf
Revises: ad423b18d25a
Create Date: 2026-06-06 14:23:49.238374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78d832902cf'
down_revision: Union[str, None] = 'ad423b18d25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        sa.table(
            "institutions",
            sa.column("id", sa.SmallInteger),
            sa.column("country_code", sa.String),
            sa.column("name", sa.String),
            sa.column("visible", sa.Boolean),
        ),
        [
            {"id": 1, "country_code": "UY", "name": "BROU", "visible": True},
            {"id": 2, "country_code": "UY", "name": "Itaú", "visible": True},
            {"id": 3, "country_code": "UY", "name": "Santander", "visible": True},
            {"id": 4, "country_code": "UY", "name": "Scotiabank", "visible": True},
            {"id": 5, "country_code": "UY", "name": "OCA", "visible": True},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institutions')
    # ### end Alembic commands ###
