"""add total_installments to purchases

Revision ID: d2a2d9f5a6e3
Revises: 8ece9281cc33
Create Date: 2026-06-11 00:17:11.994641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a2d9f5a6e3'
down_revision: Union[str, None] = '8ece9281cc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('total_installments', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'total_installments')
    # ### end Alembic commands ###
