"""create review_finding_codes

Revision ID: e212e33bdbfc
Revises: b78d832902cf
Create Date: 2026-06-06 14:25:33.212255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e212e33bdbfc'
down_revision: Union[str, None] = 'b78d832902cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_finding_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.bulk_insert(
        sa.table(
            "review_finding_codes",
            sa.column("code", sa.String),
            sa.column("message", sa.String),
        ),
        [
            {"code": "amount_above_threshold", "message": "El monto parece muy alto, ¿lo cargaste bien?"},
            {"code": "overdue_lower_than_financing", "message": "La tasa punitoria es menor que la de financiación, ¿es correcto?"},
            {"code": "rate_above_threshold", "message": "Una de las tasas parece muy alta, ¿la cargaste bien?"},
            {"code": "rates_not_updated", "message": "El resumen no trae alguna de las tasas de interés/mora o si incluyen IVA. Esos datos no se actualizarán en la tarjeta al promover; se mantienen los actuales."},
            {"code": "closing_after_due", "message": "La fecha de cierre es posterior a la de vencimiento, ¿las cargaste bien?"},
            {"code": "due_date_in_future", "message": "La fecha de vencimiento está muy adelante en el tiempo, ¿la cargaste bien?"},
            {"code": "due_date_too_old", "message": "La fecha de vencimiento es muy vieja, ¿la cargaste bien?"},
            {"code": "new_card", "message": "Este resumen no corresponde a ninguna tarjeta tuya: al confirmar se va a dar de alta una tarjeta nueva."},
            {"code": "closing_day_inferred", "message": "Pusimos el día de cierre por vos a partir del resumen. Ajustalo si tu tarjeta cierra otro día."},
            {"code": "closing_day_changed", "message": "El día de cierre de este resumen difiere del de tu tarjeta. ¿Cambió la fecha de cierre? Revisá y ajustá si corresponde."},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_finding_codes')
    # ### end Alembic commands ###
