"""create financings

Revision ID: fc4066bfbbeb
Revises: 7e12cf8ac5e3
Create Date: 2026-06-09 03:40:29.518555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4066bfbbeb'
down_revision: Union[str, None] = '7e12cf8ac5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('installment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('installment_start_date', sa.Date(), nullable=True),
    sa.Column('total_installments', sa.SmallInteger(), nullable=True),
    sa.Column('financing_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overdue_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rates_add_vat', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('usage_preference', sa.Enum('primera_opcion', 'si_necesario', 'ultimo_recurso', name='financing_usage'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financings')
    sa.Enum(name='financing_usage').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
